### PR TITLE
Fix pinging across bridges

### PR DESCRIPTION
**Pull request by VelizarHristov**
I'm about to add comments which explain why I believe this is probably the right fix, but also I recommend testing this out before trusting it.

### CODE REVIEW

**Comment by VelizarHristov** [comment]
If you look at lines 542, 596, 628, and 656, then you'll see why I believe that the block following line 656 is what gets executed when a new message gets added;

**Comment by VelizarHristov** [comment]
On line 744 or 749, the message seems to get sent across the bridge, using this method: https://discord.js.org/#/docs/main/master/class/Webhook?scrollTo=send

The first argument could be a string, or something else. Here is why I believe this is probably always going to be a string (I think):

**Comment by VelizarHristov** [comment]
Actually I suspect it might well not be a string. I added a check.

The remaining question is whether all user messages are going to be represented as a string here. Because if not, then someone might sent a non-string message which contains a @everyone ping.

**Comment by mqp** [comment]
It would have been possible to use discord.js's [`disableMentions`](https://discord.js.org/#/docs/main/master/typedef/WebhookMessageOptions) option when sending the webhook message, but that would additionally have the side effect of disabling specific-user pings. (Maybe? It's not clear to me the distinction between its `all` and `everyone` settings.)

**Pull request merged**
